### ISSUE TITLE
Add build instructions to readme.md

### ISSUE THREAD

**Issue by ghost** [pmmp/ext-chunkutils2#30]
Hi, I wanted to know if a PR that adds build instructions to the readme would be merged

I, in fact, spent about 30 minutes trying to figure out how to build this

**Comment by dktapps** [comment]
It's compiled the same way as any other PHP extension, either in-tree with `--enable-chunkutils2`, or out-of-tree using `phpize`. It's included with all PocketMine PHP builds. You can check [php-build-scripts](https://github.com/pmmp/php-build-scripts) for examples.
