### ISSUE TITLE
Error make

### ISSUE THREAD

**Issue by DeadZeta** [pmmp/ext-chunkutils2#8]
:~/php-src-php-7.2.2/ext-chunkutils2# make
/bin/bash /root/php-src-php-7.2.2/ext-chunkutils2/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++14 -fno-strict-aliasing -DGSL_THROW_ON_CONTRACT_VIOLATION=1 -I. -I/root/php-src-php-7.2.2/ext-chunkutils2 -DPHP_ATOM_INC -I/root/php-src-php-7.2.2/ext-chunkutils2/include -I/root/php-src-php-7.2.2/ext-chunkutils2/main -I/root/php-src-php-7.2.2/ext-chunkutils2 -I/etc/php7/include/php -I/etc/php7/include/php/main -I/etc/php7/include/php/TSRM -I/etc/php7/include/php/Zend -I/etc/php7/include/php/ext -I/etc/php7/include/php/ext/date/lib -I/root/php-src-php-7.2.2/ext-chunkutils2/. -I/root/php-src-php-7.2.2/ext-chunkutils2/gsl/include  -DHAVE_CONFIG_H  -g -O0   -c /root/php-src-php-7.2.2/ext-chunkutils2/chunkutils2.cpp -o chunkutils2.lo
mkdir .libs
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++14 -fno-strict-aliasing -DGSL_THROW_ON_CONTRACT_VIOLATION=1 -I. -I/root/php-src-php-7.2.2/ext-chunkutils2 -DPHP_ATOM_INC -I/root/php-src-php-7.2.2/ext-chunkutils2/include -I/root/php-src-php-7.2.2/ext-chunkutils2/main -I/root/php-src-php-7.2.2/ext-chunkutils2 -I/etc/php7/include/php -I/etc/php7/include/php/main -I/etc/php7/include/php/TSRM -I/etc/php7/include/php/Zend -I/etc/php7/include/php/ext -I/etc/php7/include/php/ext/date/lib -I/root/php-src-php-7.2.2/ext-chunkutils2/. -I/root/php-src-php-7.2.2/ext-chunkutils2/gsl/include -DHAVE_CONFIG_H -g -O0 -c /root/php-src-php-7.2.2/ext-chunkutils2/chunkutils2.cpp  -fPIC -DPIC -o .libs/chunkutils2.o
/bin/bash /root/php-src-php-7.2.2/ext-chunkutils2/libtool --mode=compile g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++14 -fno-strict-aliasing -DGSL_THROW_ON_CONTRACT_VIOLATION=1 -I. -I/root/php-src-php-7.2.2/ext-chunkutils2 -DPHP_ATOM_INC -I/root/php-src-php-7.2.2/ext-chunkutils2/include -I/root/php-src-php-7.2.2/ext-chunkutils2/main -I/root/php-src-php-7.2.2/ext-chunkutils2 -I/etc/php7/include/php -I/etc/php7/include/php/main -I/etc/php7/include/php/TSRM -I/etc/php7/include/php/Zend -I/etc/php7/include/php/ext -I/etc/php7/include/php/ext/date/lib -I/root/php-src-php-7.2.2/ext-chunkutils2/. -I/root/php-src-php-7.2.2/ext-chunkutils2/gsl/include  -DHAVE_CONFIG_H  -g -O0   -c /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp -o src/PhpPalettedBlockArray.lo
mkdir src/.libs
 g++ -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -std=c++14 -fno-strict-aliasing -DGSL_THROW_ON_CONTRACT_VIOLATION=1 -I. -I/root/php-src-php-7.2.2/ext-chunkutils2 -DPHP_ATOM_INC -I/root/php-src-php-7.2.2/ext-chunkutils2/include -I/root/php-src-php-7.2.2/ext-chunkutils2/main -I/root/php-src-php-7.2.2/ext-chunkutils2 -I/etc/php7/include/php -I/etc/php7/include/php/main -I/etc/php7/include/php/TSRM -I/etc/php7/include/php/Zend -I/etc/php7/include/php/ext -I/etc/php7/include/php/ext/date/lib -I/root/php-src-php-7.2.2/ext-chunkutils2/. -I/root/php-src-php-7.2.2/ext-chunkutils2/gsl/include -DHAVE_CONFIG_H -g -O0 -c /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp  -fPIC -DPIC -o src/.libs/PhpPalettedBlockArray.o
In file included from /etc/php7/include/php/Zend/zend_types.h:27:0,
                 from /etc/php7/include/php/Zend/zend.h:29,
                 from /etc/php7/include/php/main/php.h:35,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/ZendUtil.h:5,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:5:
/etc/php7/include/php/Zend/zend_operators.h: In function 'zend_long zend_dval_to_lval(double)':
./../main/php_config.h:2614:34: error: 'isfinite' was not declared in this scope
 #define zend_finite(a) isfinite(a)
                                  ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:114:18: note: in expansion of macro 'zend_finite'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                  ^
./../main/php_config.h:2614:34: note: suggested alternative:
 #define zend_finite(a) isfinite(a)
                                  ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:114:18: note: in expansion of macro 'zend_finite'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                  ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/gsl/include/gsl/span:24,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:2:
/usr/include/c++/5/cmath:601:5: note:   'std::isfinite'
     isfinite(_Tp __x)
     ^
In file included from /etc/php7/include/php/Zend/zend_types.h:27:0,
                 from /etc/php7/include/php/Zend/zend.h:29,
                 from /etc/php7/include/php/main/php.h:35,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/ZendUtil.h:5,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:5:
./../main/php_config.h:2594:30: error: 'isnan' was not declared in this scope
 #define zend_isnan(a) isnan(a)
                              ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:114:48: note: in expansion of macro 'zend_isnan'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                                                ^
./../main/php_config.h:2594:30: note: suggested alternative:
 #define zend_isnan(a) isnan(a)
                              ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:114:48: note: in expansion of macro 'zend_isnan'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                                                ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/gsl/include/gsl/span:24,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:2:
/usr/include/c++/5/cmath:641:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
In file included from /etc/php7/include/php/Zend/zend_types.h:27:0,
                 from /etc/php7/include/php/Zend/zend.h:29,
                 from /etc/php7/include/php/main/php.h:35,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/ZendUtil.h:5,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:5:
/etc/php7/include/php/Zend/zend_operators.h: In function 'zend_long zend_dval_to_lval_cap(double)':
./../main/php_config.h:2614:34: error: 'isfinite' was not declared in this scope
 #define zend_finite(a) isfinite(a)
                                  ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:125:18: note: in expansion of macro 'zend_finite'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                  ^
./../main/php_config.h:2614:34: note: suggested alternative:
 #define zend_finite(a) isfinite(a)
                                  ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:125:18: note: in expansion of macro 'zend_finite'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                  ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/gsl/include/gsl/span:24,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:2:
/usr/include/c++/5/cmath:601:5: note:   'std::isfinite'
     isfinite(_Tp __x)
     ^
In file included from /etc/php7/include/php/Zend/zend_types.h:27:0,
                 from /etc/php7/include/php/Zend/zend.h:29,
                 from /etc/php7/include/php/main/php.h:35,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/ZendUtil.h:5,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:5:
./../main/php_config.h:2594:30: error: 'isnan' was not declared in this scope
 #define zend_isnan(a) isnan(a)
                              ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:125:48: note: in expansion of macro 'zend_isnan'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                                                ^
./../main/php_config.h:2594:30: note: suggested alternative:
 #define zend_isnan(a) isnan(a)
                              ^
/etc/php7/include/php/Zend/zend_portability.h:312:52: note: in definition of macro 'UNEXPECTED'
 # define UNEXPECTED(condition) __builtin_expect(!!(condition), 0)
                                                    ^
/etc/php7/include/php/Zend/zend_operators.h:125:48: note: in expansion of macro 'zend_isnan'
  if (UNEXPECTED(!zend_finite(d)) || UNEXPECTED(zend_isnan(d))) {
                                                ^
In file included from /usr/include/c++/5/random:38:0,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/gsl/include/gsl/span:24,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:2:
/usr/include/c++/5/cmath:641:5: note:   'std::isnan'
     isnan(_Tp __x)
     ^
In file included from /etc/php7/include/php/Zend/zend.h:29:0,
                 from /etc/php7/include/php/main/php.h:35,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/ZendUtil.h:5,
                 from /root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:5:
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray___construct(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:209:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 1, 1)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_fromData(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:237:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 3, 3)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_get(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:297:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 3, 3)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_set(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:318:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 4, 4)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_replace(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:337:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 2, 2)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_replaceAll(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:354:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 2, 2)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_collectGarbage(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:370:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 0, 1)
  ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp: In function 'void zim_PhpPalettedBlockArray_getExpectedWordArraySize(zend_execute_data*, zval*)':
/etc/php7/include/php/Zend/zend_types.h:362:22: error: invalid conversion from 'int' to 'zend_expected_type {aka _zend_expected_type}' [-fpermissive]
 #define IS_UNDEF     0
                      ^
/etc/php7/include/php/Zend/zend_API.h:736:39: note: in expansion of macro 'IS_UNDEF'
   zend_expected_type _expected_type = IS_UNDEF; \
                                       ^
/root/php-src-php-7.2.2/ext-chunkutils2/src/PhpPalettedBlockArray.cpp:386:2: note: in expansion of macro 'ZEND_PARSE_PARAMETERS_START_EX'
  ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW, 1, 1)
  ^
Makefile:196: recipe for target 'src/PhpPalettedBlockArray.lo' failed
make: *** [src/PhpPalettedBlockArray.lo] Error 1

**Comment by dktapps** [comment]
I don't know how you've attempted to compile this, but you're doing it wrong.

**Comment by yoraze** [comment]
This error occurred because he(or she, idk) trying to compile this extension with PHP version < 7.2.9.
Versions, which are <7.1.22 or <7.2.9 has a bug, where works on C++11 extensions. This error is fixed in 7.1.22 and then merged to 7.2.9.
Look at this: https://github.com/php/php-src/commit/ad790bea2e4a8a25c79ceab964601f3785cd2bf1
